[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"


[[bin]]
name = "ir"
path = "src/main_ir.rs"


[[bin]]
name = "jit"
path = "src/main_jit.rs"


[dependencies]
dynasm = "3.0.1"
dynasmrt = "3.0.1"
